### ISSUE TITLE
Width of the generated barcode can not be changed

### ISSUE THREAD

**Issue by bobbelkl** [astrokin/EAN13BarcodeGenerator#6]
Hi Alex
I would love to use your generator but it looks like it is has a fixed width by design. Any plans to change that?

**Comment by astrokin** [comment]
Hi @bobbelkl thank you for the interest to this pod. In demo project I'm using scale to get necessary UI. It was enough atm. Could you please provide and example of your design requirements?

**Comment by bobbelkl** [comment]
Hi Alex
Thank you for replying!
In my project the ean code needs to cover almost the entire screen width (90%).
Scaling 113points to over 400 (iPhone XS Max) isn't an option.

**Comment by astrokin** [comment]
Hi @bobbelkl I've update the implementation and now you can use any width you want. Please check the latest version (0.2.0) and let me know if I can help you somehow. Thanks!
